### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [haiafara/haiafara-ro#153]
Hi...
Came across your amazing project and I really love the idea of the project... I am a Logo/Icon designer and I want to help create a Logo/Icon for your project as my Free contribution and my Love to always help give my contribution to amazing Open Source Projects.

Already working on some ideas and concept for the Logo design and i will update it here so you can give me your feedback on the design or suggest any tweaks/changes you might want to suit your needs.

Would greatly appreciate your feedback...
Regards!

**Comment by janosrusiczki** [comment]
Well this is unexpected! :smile:

Some pointers:
* haiafara is actually two words: _hai_ = come and _afară_ = outside
* the general theme is outdoors so the logo might contain a tree or a mountain
* the site is dedicated to hikers / runners / bikers

**Comment by chimzycash** [comment]
I really appreciate your response... Would finish up the logo idea concept and update it here for your feedback

**Comment by chimzycash** [comment]
Hi... Here is my idea concept design for the logo... You can give your feedback and also you can suggest any logo color of your choice to suit your needs.

![LOGO DESIGN_Haiafara_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/61212753-11f85400-a6fb-11e9-91f4-24e444ffd49c.jpg)
![LOGO DESIGN_Haiafara_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/61212755-1290ea80-a6fb-11e9-86a3-b6e5c112dc51.jpg)
![LOGO DESIGN_Haiafara_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/61212757-1290ea80-a6fb-11e9-8542-58bcb5158be2.jpg)
![LOGO DESIGN_Haiafara_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/61212758-13298100-a6fb-11e9-91cb-490c67fa8b67.jpg)
![LOGO DESIGN_Haiafara_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/61212762-13c21780-a6fb-11e9-8282-d0d96f6f7924.jpg)
![LOGO DESIGN_Haiafara_idea concept_NEW](https://user-images.githubusercontent.com/37814297/61212765-145aae00-a6fb-11e9-8e5c-aeb496cfa647.jpg)
